spring:
  security:
    user:
      name: admin
      password: 123
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${PG_HOST}:${PG_PORT}/${PG_DATABASE}?currentSchema=${PG_SCHEMA:public}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE}
      max-request-size: ${MAX_FILE_REQUEST_SIZE}

server:
  port: ${SERVER_PORT}

file:
  serverPath: ${FILE_SERVER_PATH}
  clientPath: ${FILE_CLIENT_PATH}
  url: ${FILE_SERVER_URL}
  download:
    url: ${FILE_DOWNLOAD_URL}
